version: '3.5'
services:

  node-red:
    build: ./node-red
    image: node-red-equipment
    container_name: node-red-equipment
    volumes:
      - type: volume
        source: node-red-data
        target: /data
    networks:
      - equipment      
    ports:
      - "1880:1880"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: unless-stopped

volumes:
  node-red-data:

networks:
  equipment:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.1/27
