AWSTemplateFormatVersion: "2010-09-09"
Description: IoT Chiller Demo - Core Resources
Parameters:
    DeploymentName:
        Type: String
Resources:
    notificationTopic:
        Type: AWS::SNS::Topic
        Properties:
            DisplayName: "IoT Chiller Notification Service"
            TopicName: !Sub "${DeploymentName}-notif"
    disconnectedRule:
        Type: AWS::IoT::TopicRule
        Properties: 
            RuleName: !Sub "${DeviceName}DisconnectedRule"
            TopicRulePayload: 
                Actions: 
                    - Sns:
                        MessageFormat: RAW
                        RoleArn: !GetAtt topicRuleIamRole.Arn
                        TargetArn: !Ref notificationTopic
                AwsIotSqlVersion: "2016-03-23"
                Description: Sends a notification when device is disconnected.
                RuleDisabled: false
                Sql: "SELECT * FROM '$aws/events/presence/disconnected/#'"
    unhealthyRule:
        Type: AWS::IoT::TopicRule
        Properties: 
            RuleName: !Sub "${DeviceName}UnhealthyRule"
            TopicRulePayload:
                Actions: 
                    - Sns:
                        MessageFormat: RAW
                        RoleArn: !GetAtt topicRuleIamRole.Arn
                        TargetArn: !Ref notificationTopic
                AwsIotSqlVersion: "2016-03-23"
                Description: Sends a notification when device is unhealthy.
                RuleDisabled: false
                Sql: "SELECT * FROM 'Chillers/#' WHERE message = 'UNHEALTHY'"
    topicRuleIamRole:
        Type: AWS::IAM::Role
        Properties:
            Description: The role used to send SNS notifications
            RoleName: !Sub "${DeviceName}-sns-role"
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                    Principal:
                        Service: iot.amazonaws.com
                    Action: sts:AssumeRole
            Policies:
                - PolicyName: !Sub "${DeviceName}-sns-policy"
                PolicyDocument:
                    Version: 2012-10-17
                    Statement:
                        - Effect: Allow
                        Action: 'sns:Publish'
                        Resource: !Ref notificationTopic