AWSTemplateFormatVersion: "2010-09-09"
Description: IoT Chiller Demo - Device Registration
Parameters:
    DeviceName:
        Type: String
    CertificateArn:
        Type: String
Resources:
    chillerResource:
        Type: AWS::IoT::Thing
        Properties: 
            ThingName: !Ref DeviceName
    chillerPolicy:
        Type: AWS::IoT::Policy
        Properties:
            PolicyName: !Sub "${DeviceName}-policy"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Effect: Allow
                      Action: iot:*
                      Resource: "*"
    certPolicyAttach:
        Type: AWS::IoT::PolicyPrincipalAttachment
        Properties: 
            PolicyName: !Ref chillerPolicy
            Principal: !Ref CertificateArn
    certThingAttach:
        Type: AWS::IoT::ThingPrincipalAttachment
        Properties: 
            Principal: !Ref CertificateArn
            ThingName: !Ref chillerResource
    